# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="greempackcore"
version="${file.jarVersion}"
displayName="GreemPack Core"
credits=""
authors="GreemDev"
description='''
Mod providing basic functions I couldn't find on CurseForge.
'''
[[dependencies.greempackcore]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.greempackcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
